### ISSUE TITLE
Cannot list tasks.

### ISSUE THREAD

**Issue by roberthenzel** [PiotrKowalski/image-manager#1]
Please add description to task so they can be listed with -l option.
Example:
```
proto:
   desc: "Generate pb.go files"
   summary: |
      Generate api files from proto specification
    cmds:
      - cd pkg/api/imagemanagerapis && buf mod update && buf build
      - cd pkg/api && buf generate imagemanagerapis
```
